name: Variable-Demo
on:
  workflow_dispatch:
  
env:
  APP_ENV: production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, $APP_ENV

  configuration-variable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: configuration-var demo
        run: echo Hello, ${{ vars.CONFIGURATION_VAR }}     





        

   
